name: Run examples

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        pip install ogb matplotlib
    - name: Install Spektral
      run: |
        pip install .
    - name: Just one epoch
      run: |
        sed -i -e 's/epochs = /epochs = 1 #/g' examples/node_prediction/*.py
        sed -i -e 's/epochs = /epochs = 1 #/g' examples/graph_prediction/*.py
        sed -i -e 's/epochs = /epochs = 1 #/g' examples/other/*.py
    - name: Run all examples
      run: |
        cd examples/node_prediction/
        for f in *.py; do
          echo "##### $f #####"
          python $f
        done
        cd ..
        cd graph_prediction/
        for f in *.py; do
          echo "##### $f #####"
          python $f
        done
        cd ..
        cd other/
        for f in *.py; do
          echo "##### $f #####"
          python $f
        done
        cd ..
